# Generated by Django 3.1 on 2022-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galarymodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galarymodel',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
