# Generated by Django 3.1 on 2022-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STApp', '0002_auto_20220126_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galarymodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
